import { SHAPES_DATABASE, SHAPE_COLORS } from './shapeGenerator';

export const generateOfflineBundle = async () => {
  // Safe extraction of all active document styles to maintain current CSS state
  let globalStyleRules = '';
  for (const sheet of Array.from(document.styleSheets)) {
    try {
      for (const rule of Array.from(sheet.cssRules)) {
        globalStyleRules += rule.cssText + '\n';
      }
    } catch (e) {
      // Absorb cross-origin asset boundary restrictions silently
    }
  }

  // Standalone page build architecture
  const pageSegments = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '    <meta charset="UTF-8">',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">',
    '    <title>Block Blast Pro - Offline Runtime Engine</title>',
    '    <style>',
    '        /* Core Google Font Delivery Fallback Engine */',
    '        @import url("https://fonts.googleapis.com/css2?family=Comfortaa:wght@700&family=Source+Sans+Pro:wght@400;600;700&display=swap");',
    '        ',
    '        :root {',
    '            --bg-color: #0a0a0a;',
    '            --text-color: #f5f5f5;',
    '            --surface-color: rgba(255,255,255,0.06);',
    '            --border-color: rgba(255,255,255,0.12);',
    '            --primary-accent: #95e2fc; /* Specific Requested Sky Blue Accent */',
    '            --font-display: "Comfortaa", system-ui, sans-serif;',
    '            --font-body: "Source Sans Pro", system-ui, sans-serif;',
    '            --grid-cell-empty: rgba(0, 0, 0, 0.25);',
    '            --card-shadow: 0 8px 32px rgba(0,0,0,0.5);',
    '        }',
    '        ',
    '        [data-theme="light"] {',
    '            --bg-color: #f5f5f5;',
    '            --text-color: #171717;',
    '            --surface-color: rgba(0,0,0,0.04);',
    '            --border-color: rgba(0,0,0,0.08);',
    '            --grid-cell-empty: rgba(0, 0, 0, 0.05);',
    '            --card-shadow: 0 8px 24px rgba(0,0,0,0.1);',
    '        }',
    '        ',
    '        body {',
    '            margin: 0; padding: 0; touch-action: none;',
    '            background-color: var(--bg-color); color: var(--text-color);',
    '            font-family: var(--font-body); user-select: none; -webkit-user-select: none;',
    '            display: flex; justify-content: center; min-height: 100vh;',
    '            transition: background-color 0.3s ease, color 0.3s ease;',
    '        }',
    '        ',
    '        h1, h2, h3, .title-font { font-family: var(--font-display); font-weight: 700; }',
    '        ',
    '        .main-wrapper {',
    '            width: 100%; max-width: 480px; display: flex; flex-direction: column;',
    '            justify-content: space-between; padding: 1rem; box-sizing: border-box;',
    '        }',
    '        ',
    '        .game-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem; }',
    '        ',
    '        .score-panel {',
    '            display: flex; justify-content: space-between; align-items: center;',
    '            background: var(--surface-color); padding: 0.75rem 1rem; border-radius: 1rem;',
    '            border: 1px solid var(--border-color); margin-bottom: 1rem; font-weight: 600;',
    '        }',
    '        ',
    '        .currency-counter { color: #fbbf24; display: flex; align-items: center; gap: 0.25rem; font-weight: 700; }',
    '        ',
    '        .grid-frame {',
    '            width: 100%; aspect-ratio: 1; background: var(--surface-color);',
    '            border: 2px solid var(--border-color); border-radius: 1.25rem; padding: 0.5rem;',
    '            box-sizing: border-box; display: grid; gap: 4px; position: relative;',
    '        }',
    '        ',
    '        .cell-unit {',
    '            background: var(--grid-cell-empty); border-radius: 6px; width: 100%; height: 100%;',
    '            position: relative; box-sizing: border-box; transition: background-color 0.15s ease;',
    '        }',
    '        ',
    '        .has-shadow { box-shadow: 0 4px 6px rgba(0,0,0,0.15), inset 0 1px 1px rgba(255,255,255,0.2); }',
    '        ',
    '        .tray-area {',
    '            display: grid; grid-template-columns: repeat(3, 1fr); gap: 0.75rem;',
    '            margin-top: 1.25rem; min-height: 110px;',
    '        }',
    '        ',
    '        .tray-dock {',
    '            background: var(--surface-color); border: 2px dashed var(--border-color);',
    '            aspect-ratio: 1; border-radius: 1rem; display: flex; align-items: center;',
    '            justify-content: center; position: relative; cursor: grab; transition: transform 0.2s;',
    '        }',
    '        ',
    '        .tray-dock:active { cursor: grabbing; }',
    '        ',
    '        .floating-drag-element {',
    '            position: fixed; pointer-events: none; z-index: 99999;',
    '            transform: scale(1.2) translateY(-40px); opacity: 0.9; transform-origin: center center;',
    '        }',
    '        ',
    '        .ui-modal {',
    '            position: fixed; inset: 0; background: rgba(0,0,0,0.75);',
    '            backdrop-filter: blur(8px); display: none; align-items: center;',
    '            justify-content: center; z-index: 50000; padding: 1rem;',
    '        }',
    '        .ui-modal.is-open { display: flex; }',
    '        ',
    '        .modal-body {',
    '            background: #171717; border: 1px solid var(--border-color); width: 100%;',
    '            max-width: 360px; border-radius: 1.5rem; padding: 1.5rem; box-shadow: var(--card-shadow);',
    '            color: #ffffff; box-sizing: border-box; overflow-y: auto; max-height: 85vh;',
    '        }',
    '        [data-theme="light"] .modal-body { background: #ffffff; color: #171717; }',
    '        ',
    '        .control-row { display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.25rem; }',
    '        ',
    '        .action-button {',
    '            background: var(--primary-accent); border: none; padding: 0.6rem 1.2rem;',
    '            border-radius: 0.75rem; font-family: var(--font-display); color: #000000;',
    '            font-weight: 700; cursor:pointer; width: 100%; text-align: center; margin-top: 0.5rem;',
    '        }',
    '        ',
    '        .theme-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 0.5rem; margin-top: 0.5rem; }',
    '        .theme-swatch { height: 36px; border-radius: 0.5rem; border: 2px solid transparent; cursor: pointer; position: relative; }',
    '        .theme-swatch.active-swatch { border-color: var(--primary-accent); }',
    '        ',
    '        .size-selector { display: flex; gap: 0.5rem; margin-bottom: 1rem; }',
    '        .size-btn { flex: 1; background: var(--surface-color); border: 1px solid var(--border-color); color: inherit; padding: 0.5rem; border-radius: 0.5rem; cursor: pointer; font-family: var(--font-display); font-weight: 700; }',
    '        .size-btn.active-size { background: var(--primary-accent); color: #000; border-color: var(--primary-accent); }',
    '        .helper-text { font-size: 10px; opacity: 0.6; text-align: center; display: block; width:100%; }',
    globalStyleRules,
    '    </style>',
    '</head>',
    '<body>',
    '    <div class="main-wrapper">',
    '        <div class="game-header">',
    '            <h1 style="margin:0; font-size:1.6rem;" class="title-font">Block Blast</h1>',
    '            <div style="display: flex; gap: 0.6rem; align-items: center;">',
    '                <div class="currency-counter">🪙 <span id="balance-txt">0</span></div>',
    '                <button id="trigger-shop" style="background:none; border:none; font-size:1.4rem; cursor:pointer;">🛒</button>',
    '                <button id="trigger-settings" style="background:none; border:none; font-size:1.4rem; cursor:pointer;">⚙️</button>',
    '            </div>',
    '        </div>',
    '        ',
    '        <div class="score-panel">',
    '            <div>Score: <span id="score-txt" style="color:var(--primary-accent);">0</span></div>',
    '            <div style="font-size: 0.85rem; opacity: 0.8;">Combo: <span id="combo-txt">0</span> (x<span id="mult-txt">1.0</span>)</div>',
    '            <div>High: <span id="high-txt">0</span></div>',
    '        </div>',
    '        ',
    '        <div id="grid-root" class="grid-frame"></div>',
    '        <div id="tray-root" class="tray-area"></div>',
    '    </div>',
    '    ',
    '    ',
    '    <div id="modal-settings" class="ui-modal">',
    '        <div class="modal-body">',
    '            <h3 class="title-font" style="margin-top:0; margin-bottom:1.5rem; font-size:1.3rem;">Game Controls</h3>',
    '            ',
    '            <div class="control-row">',
    '                <span>Dark Mode Skin</span>',
    '                <input type="checkbox" id="toggle-dark" checked>',
    '            </div>',
    '            <div class="control-row">',
    '                <span>Render Block Shadows</span>',
    '                <input type="checkbox" id="toggle-shadow" checked>',
    '            </div>',
    '            <div class="control-row">',
    '                <span>Display Matrix Names</span>',
    '                <input type="checkbox" id="toggle-names">',
    '            </div>',
    '            <div class="control-row" id="pwa-row" style="display:none;">',
    '                <span>Standalone App</span>',
    '                <button id="btn-pwa-install" style="font-size:0.8rem; padding:0.25rem 0.6rem;">Install</button>',
    '            </div>',
    '            <div class="control-row">',
    '                <span>Fullscreen Toggle</span>',
    '                <button id="btn-fullscreen-toggle" style="font-size:0.8rem; padding:0.25rem 0.6rem;">Toggle</button>',
    '            </div>',
    '            ',
    '            <button id="close-settings" class="action-button">Save & Exit</button>',
    '        </div>',
    '    </div>',
    '    ',
    '    ',
    '    <div id="modal-shop" class="ui-modal">',
    '        <div class="modal-body">',
    '            <h3 class="title-font" style="margin-top:0; margin-bottom:1rem; font-size:1.3rem;">Cosmetic Engine</h3>',
    '            ',
    '            <label style="font-weight:600; font-size:0.9rem; display:block; margin-bottom:0.5rem;">Grid Layout Size</label>',
    '            <div class="size-selector">',
    '                <button class="size-btn active-size" data-size="6">6x6</button>',
    '                <button class="size-btn" data-size="8">8x8</button>',
    '                <button class="size-btn" data-size="10">10x10</button>',
    '            </div>',
    '            ',
    '            <label style="font-weight:600; font-size:0.9rem; display:block; margin-bottom:0.25rem;">Color Themes (16 Pool Selection)</label>',
    '            <span style="font-size:11px; opacity:0.7; display:block; margin-bottom:0.5rem;">Active palette rotates automatically upon every full-line clear sweep.</span>',
    '            <div id="swatch-container" class="theme-grid"></div>',
    '            ',
    '            <button id="close-shop" class="action-button" style="margin-top:1.5rem;">Confirm Configuration</button>',
    '        </div>',
    '    </div>',
    '    ',
    '    <script>',
    `        const SHAPES_ENGINE = ${JSON.stringify(SHAPES_DATABASE)};`,
    `        const THEME_PALETTES = ${JSON.stringify(SHAPE_COLORS.slice(0, 16).length === 16 ? SHAPE_COLORS.slice(0, 16) : [...SHAPE_COLORS, "#3b82f6", "#ef4444", "#10b981", "#f59e0b", "#ec4899", "#8b5cf6", "#6366f1", "#14b8a6"].slice(0,16))};`,
    '        ',
    '        let gameState = {',
    '            gridSize: 6, // Default 6x6 configuration applied on standalone execution initialization',
    '            score: 0,',
    '            combo: 0,',
    '            multiplier: 1.0,',
    '            highScore: parseInt(localStorage.getItem("bb_high_offline") || "0"),',
    '            balance: parseInt(localStorage.getItem("bb_bal_offline") || "0"),',
    '            activePaletteIdx: 0,',
    '            useShadows: true,',
    '            showNames: false',
    '        };',
    '        ',
    '        let board = [];',
    '        let trayHand = [null, null, null];',
    '        let currentDrag = null;',
    '        let deferredPrompt = null;',
    '        ',
    '        const elGrid = document.getElementById("grid-root");',
    '        const elTray = document.getElementById("tray-root");',
    '        ',
    '        function buildBoard() {',
    '            board = Array(gameState.gridSize).fill(null).map(() => Array(gameState.gridSize).fill(null));',
    '            elGrid.style.gridTemplateRows = `repeat(${gameState.gridSize}, 1fr)`;',
    '            elGrid.style.gridTemplateColumns = `repeat(${gameState.gridSize}, 1fr)`;',
    '            drawBoard();',
    '        }',
    '        ',
    '        function drawBoard() {',
    '            elGrid.innerHTML = "";',
    '            for(let r=0; r<gameState.gridSize; r++) {',
    '                for(let c=0; c<gameState.gridSize; c++) {',
    '                    const cell = document.createElement("div");',
    '                    cell.className = "cell-unit";',
    '                    cell.dataset.row = r;',
    '                    cell.dataset.col = c;',
    '                    if(board[r][c]) {',
    '                        cell.style.backgroundColor = board[r][c];',
    '                        if(gameState.useShadows) cell.classList.add("has-shadow");',
    '                    }',
    '                    elGrid.appendChild(cell);',
    '                }',
    '            }',
    '        }',
    '        ',
    '        function loadTrayHand() {',
    '            const shapeKeys = Object.keys(SHAPES_ENGINE);',
    '            for(let i=0; i<3; i++) {',
    '                const randomKey = shapeKeys[Math.floor(Math.random() * shapeKeys.length)];',
    '                const colorHex = THEME_PALETTES[(gameState.activePaletteIdx + i) % THEME_PALETTES.length];',
    '                trayHand[i] = { ',
    '                    matrix: SHAPES_ENGINE[randomKey].cells || SHAPES_ENGINE[randomKey], ',
    '                    name: SHAPES_ENGINE[randomKey].name || randomKey,',
    '                    color: colorHex ',
    '                };',
    '            }',
    '            drawTray();',
    '        }',
    '        ',
    '        function drawTray() {',
    '            elTray.innerHTML = "";',
    '            trayHand.forEach((shape, idx) => {',
    '                const dock = document.createElement("div");',
    '                dock.className = "tray-dock";',
    '                dock.dataset.slotIndex = idx;',
    '                ',
    '                if(shape) {',
    '                    const matrix = shape.matrix;',
    '                    const previewWrap = document.createElement("div");',
    '                    previewWrap.style.display = "grid";',
    '                    previewWrap.style.gridTemplateRows = `repeat(${matrix.length}, 14px)`;',
    '                    previewWrap.style.gridTemplateColumns = `repeat(${matrix[0].length}, 14px)`;',
    '                    previewWrap.style.gap = "2px";',
    '                    ',
    '                    matrix.forEach(row => {',
    '                        row.forEach(val => {',
    '                            const block = document.createElement("div");',
    '                            block.style.borderRadius = "3px";',
    '                            if(val) {',
    '                                block.style.backgroundColor = shape.color;',
    '                                if(gameState.useShadows) block.classList.add("has-shadow");',
    '                            }',
    '                            previewWrap.appendChild(block);',
    '                        });',
    '                    });',
    '                    ',
    '                    dock.appendChild(previewWrap);',
    '                    ',
    '                    if(gameState.showNames) {',
    '                        const nameLabel = document.createElement("span");',
    '                        nameLabel.innerText = shape.name;',
    '                        nameLabel.className = "helper-text";',
    '                        nameLabel.style.position = "absolute";',
    '                        nameLabel.style.bottom = "4px";',
    '                        dock.appendChild(nameLabel);',
    '                    }',
    '                    ',
    '                    dock.addEventListener("pointerdown", (e) => beginDragSequence(e, idx));',
    '                }',
    '                elTray.appendChild(dock);',
    '            });',
    '        }',
    '        ',
    '        function beginDragSequence(e, slotIndex) {',
    '            e.preventDefault();',
    '            const targetShape = trayHand[slotIndex];',
    '            if(!targetShape) return;',
    '            ',
    '            const sourceDock = e.currentTarget;',
    '            const clonedRender = sourceDock.cloneNode(true);',
    '            clonedRender.classList.add("floating-drag-element");',
    '            document.body.appendChild(clonedRender);',
    '            ',
    '            currentDrag = {',
    '                slotIndex: slotIndex,',
    '                shape: targetShape,',
    '                element: clonedRender',
    '            };',
    '            ',
    '            trackPosition(e);',
    '            document.addEventListener("pointermove", processDragMove);',
    '            document.addEventListener("pointerup", terminateDragSequence);',
    '        }',
    '        ',
    '        function trackPosition(e) {',
    '            if(!currentDrag) return;',
    '            currentDrag.element.style.left = `${e.clientX - 55}px`;',
    '            currentDrag.element.style.top = `${e.clientY - 45}px`;',
    '        }',
    '        ',
    '        function processDragMove(e) { if(currentDrag) trackPosition(e); }',
    '        ',
    '        function terminateDragSequence(e) {',
    '            if(!currentDrag) return;',
    '            document.removeEventListener("pointermove", processDragMove);',
    '            document.removeEventListener("pointerup", terminateDragSequence);',
    '            currentDrag.element.remove();',
    '            ',
    '            const underPoint = document.elementFromPoint(e.clientX, e.clientY);',
    '            const targetCell = underPoint ? underPoint.closest(".cell-unit") : null;',
    '            ',
    '            if(targetCell) {',
    '                const startRow = parseInt(targetCell.dataset.row);',
    '                const startCol = parseInt(targetCell.dataset.col);',
    '                ',
    '                if(verifyPlacementFit(currentDrag.shape.matrix, startRow, startCol)) {',
    '                    applyMatrixToBoard(currentDrag.shape.matrix, currentDrag.shape.color, startRow, startCol);',
    '                    trayHand[currentDrag.slotIndex] = null;',
    '                    ',
    '                    if(trayHand.every(s => s === null)) {',
    '                        loadTrayHand();',
    '                    } else {',
    '                        drawTray();',
    '                    }',
    '                }',
    '            }',
    '            currentDrag = null;',
    '        }',
    '        ',
    '        function verifyPlacementFit(matrix, sRow, sCol) {',
    '            for(let r=0; r<matrix.length; r++) {',
    '                for(let c=0; c<matrix[r].length; c++) {',
    '                    if(matrix[r][c]) {',
    '                        const tr = sRow + r;',
    '                        const tc = sCol + c;',
    '                        if(tr >= gameState.gridSize || tc >= gameState.gridSize || tr < 0 || tc < 0 || board[tr][tc]) {',
    '                            return false;',
    '                        }',
    '                    }',
    '                }',
    '            }',
    '            return true;',
    '        }',
    '        ',
    '        function applyMatrixToBoard(matrix, colorHex, sRow, sCol) {',
    '            for(let r=0; r<matrix.length; r++) {',
    '                for(let c=0; c<matrix[r].length; c++) {',
    '                    if(matrix[r][c]) board[sRow+r][sCol+c] = colorHex;',
    '                }',
    '            }',
    '            gameState.score += 15;',
    '            gameState.balance += 1;',
    '            sweepCompleteLines();',
    '            drawBoard();',
    '            refreshScoreboard();',
    '        }',
    '        ',
    '        function sweepCompleteLines() {',
    '            let fullyClearedRows = [];',
    '            let fullyClearedCols = [];',
    '            ',
    '            for(let r=0; r<gameState.gridSize; r++) {',
    '                if(board[r].every(c => c !== null)) fullyClearedRows.push(r);',
    '            }',
    '            for(let c=0; c<gameState.gridSize; c++) {',
    '                let targetColMatch = true;',
    '                for(let r=0; r<gameState.gridSize; r++) {',
    '                    if(board[r][c] === null) { targetColMatch = false; break; }',
    '                }',
    '                if(targetColMatch) fullyClearedCols.push(c);',
    '            }',
    '            ',
    '            const linesCleared = fullyClearedRows.length + fullyClearedCols.length;',
    '            if(linesCleared > 0) {',
    '                fullyClearedRows.forEach(r => board[r].fill(null));',
    '                fullyClearedCols.forEach(c => {',
    '                    for(let r=0; r<gameState.gridSize; r++) board[r][c] = null;',
    '                });',
    '                ',
    '                gameState.combo++;',
    '                let rawPoints = linesCleared * 120;',
    '                gameState.score += Math.floor(rawPoints * gameState.multiplier);',
    '                gameState.multiplier += 0.4 * linesCleared;',
    '                gameState.balance += linesCleared * 6;',
    '                ',
    '                /* 16 Color Swatch Palette Auto Rotation Event Hook Trigger */',
    '                gameState.activePaletteIdx = (gameState.activePaletteIdx + 1) % THEME_PALETTES.length;',
    '                updateActiveSwatchHighlight();',
    '            } else {',
    '                gameState.combo = 0;',
    '                gameState.multiplier = 1.0;',
    '            }',
    '            ',
    '            if(gameState.score > gameState.highScore) {',
    '                gameState.highScore = gameState.score;',
    '                localStorage.setItem("bb_high_offline", gameState.highScore.toString());',
    '            }',
    '            localStorage.setItem("bb_bal_offline", gameState.balance.toString());',
    '        }',
    '        ',
    '        function refreshScoreboard() {',
    '            document.getElementById("score-txt").innerText = gameState.score;',
    '            document.getElementById("combo-txt").innerText = gameState.combo;',
    '            document.getElementById("mult-txt").innerText = gameState.multiplier.toFixed(1);',
    '            document.getElementById("high-txt").innerText = gameState.highScore;',
    '            document.getElementById("balance-txt").innerText = gameState.balance;',
    '        }',
    '        ',
    '        /* Modals View Interactions Management Layer */',
    '        document.getElementById("trigger-settings").addEventListener("click", () => document.getElementById("modal-settings").classList.add("is-open"));',
    '        document.getElementById("close-settings").addEventListener("click", () => document.getElementById("modal-settings").classList.remove("is-open"));',
    '        ',
    '        document.getElementById("trigger-shop").addEventListener("click", () => document.getElementById("modal-shop").classList.add("is-open"));',
    '        document.getElementById("close-shop").addEventListener("click", () => document.getElementById("modal-shop").classList.remove("is-open"));',
    '        ',
    '        document.getElementById("toggle-dark").addEventListener("change", (e) => {',
    '            document.documentElement.setAttribute("data-theme", e.target.checked ? "dark" : "light");',
    '        });',
    '        ',
    '        document.getElementById("toggle-shadow").addEventListener("change", (e) => {',
    '            gameState.useShadows = e.target.checked;',
    '            drawBoard();',
    '            drawTray();',
    '        });',
    '        ',
    '        document.getElementById("toggle-names").addEventListener("change", (e) => {',
    '            gameState.showNames = e.target.checked;',
    '            drawTray();',
    '        });',
    '        ',
    '        document.getElementById("btn-fullscreen-toggle").addEventListener("click", () => {',
    '            if (!document.fullscreenElement) {',
    '                document.documentElement.requestFullscreen().catch(() => {});',
    '            } else {',
    '                document.exitFullscreen();',
    '            }',
    '        });',
    '        ',
    '        /* Shop Dimensions Adjustments Controls Configuration */',
    '        document.querySelectorAll(".size-btn").forEach(btn => {',
    '            btn.addEventListener("click", (e) => {',
    '                document.querySelectorAll(".size-btn").forEach(b => b.classList.remove("active-size"));',
    '                e.target.classList.add("active-size");',
    '                gameState.gridSize = parseInt(e.target.dataset.size);',
    '                gameState.score = 0; gameState.combo = 0; gameState.multiplier = 1.0;',
    '                buildBoard(); refreshScoreboard();',
    '            });',
    '        });',
    '        ',
    '        /* Swatch Matrix Generator */',
    '        const swatchFrame = document.getElementById("swatch-container");',
    '        THEME_PALETTES.forEach((hex, sIdx) => {',
    '            const swatch = document.createElement("div");',
    '            swatch.className = "theme-swatch";',
    '            swatch.style.backgroundColor = hex;',
    '            swatch.dataset.index = sIdx;',
    '            if(sIdx === gameState.activePaletteIdx) swatch.classList.add("active-swatch");',
    '            ',
    '            swatch.addEventListener("click", (e) => {',
    '                gameState.activePaletteIdx = parseInt(e.target.dataset.index);',
    '                updateActiveSwatchHighlight();',
    '                drawTray();',
    '            });',
    '            swatchFrame.appendChild(swatch);',
    '        });',
    '        ',
    '        function updateActiveSwatchHighlight() {',
    '            document.querySelectorAll(".theme-swatch").forEach(s => {',
    '                s.classList.remove("active-swatch");',
    '                if(parseInt(s.dataset.index) === gameState.activePaletteIdx) s.classList.add("active-swatch");',
    '            });',
    '        }',
    '        ',
    '        /* Progressive Web App Initialization Listeners hook */',
    '        window.addEventListener("beforeinstallprompt", (e) => {',
    '            e.preventDefault(); deferredPrompt = e;',
    '            document.getElementById("pwa-row").style.display = "flex";',
    '        });',
    '        ',
    '        document.getElementById("btn-pwa-install").addEventListener("click", () => {',
    '            if(!deferredPrompt) return;',
    '            deferredPrompt.prompt();',
    '            deferredPrompt.userChoice.then(() => {',
    '                document.getElementById("pwa-row").style.display = "none";',
    '                deferredPrompt = null;',
    '            });',
    '        });',
    '        ',
    '        // Boot Sequence Execution Context',
    '        buildBoard();',
    '        loadTrayHand();',
    '        refreshScoreboard();',
    '    </script>',
    '</body>',
    '</html>'
  ].join('\n');

  try {
    const blob = new Blob([pageSegments], { type: 'text/html;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    
    const downloadBridgeLink = document.createElement('a');
    downloadBridgeLink.href = url;
    downloadBridgeLink.download = 'block-blast-offline.html';
    document.body.appendChild(downloadBridgeLink);
    downloadBridgeLink.click();
    
    setTimeout(() => {
      document.body.removeChild(downloadBridgeLink);
      URL.revokeObjectURL(url);
    }, 200);
  } catch (downloadException) {
    console.error("The offline download operation encountered a critical file system stream write error:", downloadException);
    alert("Download Error: Standalone construction stream blocked by browser context.");
  }
};
