import { SHAPES_DATABASE, SHAPE_COLORS } from './shapeGenerator';

export const generateOfflineBundle = async () => {
  // Safe extraction of active document rules
  let globalStyleRules = '';
  for (const sheet of Array.from(document.styleSheets)) {
    try {
      for (const rule of Array.from(sheet.cssRules)) {
        globalStyleRules += rule.cssText + '\n';
      }
    } catch (e) {
      // Absorb cross-origin asset boundaries gracefully
    }
  }

  const htmlContent = [
    '<!DOCTYPE html>',
    '<html lang="en" data-theme="dark">',
    '<head>',
    '    <meta charset="UTF-8">',
    '    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover">',
    '    <title>Block Blast Pro - Standalone Engine</title>',
    '    <style>',
    '        @import url("https://fonts.googleapis.com/css2?family=Comfortaa:wght@700&family=Source+Sans+Pro:wght@400;600;700&display=swap");',
    '        ',
    '        :root {',
    '            --bg-color: #0b0f19;',
    '            --text-color: #f8fafc;',
    '            --surface-color: #1e293b;',
    '            --border-color: #334155;',
    '            --primary-accent: #95e2fc;',
    '            --font-display: "Comfortaa", system-ui, sans-serif;',
    '            --font-body: "Source Sans Pro", system-ui, sans-serif;',
    '            --grid-cell-empty: #111827;',
    '            --card-shadow: 0 12px 40px rgba(0, 0, 0, 0.6);',
    '            --block-shadow: 0 6px 12px rgba(0, 0, 0, 0.5);',
    '        }',
    '        ',
    '        [data-theme="light"] {',
    '            --bg-color: #f8fafc;',
    '            --text-color: #0f172a;',
    '            --surface-color: #ffffff;',
    '            --border-color: #e2e8f0;',
    '            --grid-cell-empty: #cbd5e1;',
    '            --card-shadow: 0 12px 30px rgba(15, 23, 42, 0.08);',
    '            --block-shadow: 0 4px 8px rgba(15, 23, 42, 0.15);',
    '        }',
    '        ',
    '        * { box-sizing: border-box; -webkit-tap-highlight-color: transparent; }',
    '        body {',
    '            margin: 0; padding: 0; touch-action: none;',
    '            background-color: var(--bg-color); color: var(--text-color);',
    '            font-family: var(--font-body); user-select: none; -webkit-user-select: none;',
    '            display: flex; justify-content: center; min-height: 100vh;',
    '            transition: background-color 0.25s ease, color 0.25s ease;',
    '        }',
    '        ',
    '        h1, h2, h3, .title-font { font-family: var(--font-display); font-weight: 700; }',
    '        ',
    '        .main-wrapper {',
    '            width: 100%; max-width: 460px; display: flex; flex-direction: column;',
    '            justify-content: flex-start; padding: 1.25rem; gap: 1rem;',
    '        }',
    '        ',
    '        .game-header { display: flex; justify-content: space-between; align-items: center; }',
    '        ',
    '        .score-panel {',
    '            display: flex; justify-content: space-between; align-items: center;',
    '            background: var(--surface-color); padding: 1rem; border-radius: 1.25rem;',
    '            border: 1px solid var(--border-color); box-shadow: var(--card-shadow); font-weight: 600;',
    '        }',
    '        ',
    '        .currency-counter { color: #fbbf24; display: flex; align-items: center; gap: 0.35rem; font-weight: 700; }',
    '        ',
    '        .grid-frame {',
    '            width: 100%; aspect-ratio: 1; background: var(--surface-color);',
    '            border: 3px solid var(--border-color); border-radius: 1.5rem; padding: 0.75rem;',
    '            display: grid; gap: 6px; box-shadow: var(--card-shadow);',
    '        }',
    '        ',
    '        .cell-unit {',
    '            background: var(--grid-cell-empty); border-radius: 8px; width: 100%; height: 100%;',
    '            position: relative; transition: background-color 0.1s, transform 0.1s;',
    '        }',
    '        ',
    '        .has-shadow { box-shadow: var(--block-shadow); border: 1px solid rgba(255,255,255,0.15); }',
    '        [data-theme="light"] .has-shadow { border: 1px solid rgba(0,0,0,0.1); }',
    '        ',
    '        .tray-area {',
    '            display: grid; grid-template-columns: repeat(3, 1fr); gap: 1rem;',
    '            margin-top: 0.5rem; min-height: 120px;',
    '        }',
    '        ',
    '        .tray-dock {',
    '            background: var(--surface-color); border: 2px dashed var(--border-color);',
    '            aspect-ratio: 1; border-radius: 1.25rem; display: flex; flex-direction: column;',
    '            align-items: center; justify-content: center; position: relative; cursor: grab;',
    '            box-shadow: inset 0 2px 8px rgba(0,0,0,0.2); transition: transform 0.2s, background-color 0.2s;',
    '        }',
    '        ',
    '        .floating-drag-element {',
    '            position: fixed; pointer-events: none; z-index: 99999;',
    '            transform: scale(1.1); filter: drop-shadow(0 15px 15px rgba(0,0,0,0.4));',
    '        }',
    '        ',
    '        .ui-modal {',
    '            position: fixed; inset: 0; background: rgba(15, 23, 42, 0.85);',
    '            backdrop-filter: blur(12px); display: none; align-items: center;',
    '            justify-content: center; z-index: 50000; padding: 1.2rem;',
    '        }',
    '        .ui-modal.is-open { display: flex; }',
    '        ',
    '        .modal-body {',
    '            background: var(--surface-color); border: 2px solid var(--border-color); width: 100%;',
    '            max-width: 380px; border-radius: 1.75rem; padding: 1.75rem; box-shadow: var(--card-shadow);',
    '            color: var(--text-color); overflow-y: auto; max-height: 85vh;',
    '        }',
    '        ',
    '        .control-row { display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem; }',
    '        ',
    '        /* Premium Custom Toggle Switches Replacing Checkboxes */',
    '        .switch-frame {',
    '            position: relative; display: inline-block; width: 50px; height: 26px;',
    '        }',
    '        .switch-frame input { opacity: 0; width: 0; height: 0; }',
    '        .switch-slider {',
    '            position: absolute; cursor: pointer; inset: 0; background-color: #475569;',
    '            transition: .3s; border-radius: 34px;',
    '        }',
    '        .switch-slider:before {',
    '            position: absolute; content: ""; height: 18px; width: 18px; left: 4px; bottom: 4px;',
    '            background-color: white; transition: .3s; border-radius: 50%;',
    '        }',
    '        input:checked + .switch-slider { background-color: var(--primary-accent); }',
    '        input:checked + .switch-slider:before { transform: translateX(24px); }',
    '        [data-theme="light"] input:checked + .switch-slider:before { background-color: #0f172a; }',
    '        ',
    '        .action-button {',
    '            background: var(--primary-accent); border: none; padding: 0.75rem 1.5rem;',
    '            border-radius: 1rem; font-family: var(--font-display); color: #0f172a;',
    '            font-weight: 700; cursor: pointer; width: 100%; text-align: center;',
    '            box-shadow: 0 4px 12px rgba(149, 226, 252, 0.3); transition: all 0.2s;',
    '        }',
    '        .action-button:hover { transform: translateY(-1px); filter: brightness(1.05); }',
    '        ',
    '        .theme-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 0.65rem; margin-top: 0.75rem; }',
    '        .theme-swatch {',
    '            height: 42px; border-radius: 0.75rem; border: 3px solid transparent;',
    '            cursor: pointer; position: relative; box-shadow: var(--block-shadow);',
    '            display: flex; align-items: center; justify-content: center; font-size: 10px;',
    '        }',
    '        .theme-swatch.active-swatch { border-color: var(--primary-accent); }',
    '        .theme-swatch.locked-swatch::after { content: "🔒"; font-size: 0.75rem; }',
    '        ',
    '        .size-selector { display: grid; grid-template-columns: repeat(3, 1fr); gap: 0.5rem; margin-top: 0.5rem; margin-bottom: 1.5rem; }',
    '        .size-btn { ',
    '            background: var(--bg-color); border: 2px solid var(--border-color); color: inherit; ',
    '            padding: 0.6rem; border-radius: 0.75rem; cursor: pointer; font-family: var(--font-display); ',
    '            font-weight: 700; text-align: center; position: relative;',
    '        }',
    '        .size-btn.active-size { background: var(--primary-accent); color: #0f172a; border-color: var(--primary-accent); }',
    '        .size-btn.locked-size::after { content: " 🔒"; font-size: 0.7rem; opacity: 0.8; }',
    '        .helper-text { font-size: 11px; opacity: 0.6; text-align: center; display: block; width: 100%; margin-top: 4px; }',
    '    </style>',
    '</head>',
    '<body>',
    '    <div class="main-wrapper">',
    '        <div class="game-header">',
    '            <h1 style="margin:0; font-size:1.75rem; color: var(--primary-accent);" class="title-font">Block Blast</h1>',
    '            <div style="display: flex; gap: 0.75rem; align-items: center;">',
    '                <div class="currency-counter">🪙 <span id="balance-txt">0</span></div>',
    '                <button id="trigger-shop" style="background:none; border:none; font-size:1.5rem; cursor:pointer;">🛒</button>',
    '                <button id="trigger-settings" style="background:none; border:none; font-size:1.5rem; cursor:pointer;">⚙️</button>',
    '            </div>',
    '        </div>',
    '        ',
    '        <div class="score-panel">',
    '            <div>Score: <span id="score-txt" style="color:var(--primary-accent); font-size:1.2rem;">0</span></div>',
    '            <div style="font-size: 0.85rem; opacity: 0.9; text-align: center;">Combo: <span id="combo-txt">0</span><br><span style="color:#fbbf24;" id="mult-txt">x1.0</span></div>',
    '            <div>High: <span id="high-txt">0</span></div>',
    '        </div>',
    '        ',
    '        <div id="grid-root" class="grid-frame"></div>',
    '        <div id="tray-root" class="tray-area"></div>',
    '    </div>',
    '    ',
    '    ',
    '    <div id="modal-settings" class="ui-modal">',
    '        <div class="modal-body">',
    '            <h3 class="title-font" style="margin-top:0; margin-bottom:1.5rem; font-size:1.4rem; text-align:center;">Settings</h3>',
    '            ',
    '            <div class="control-row">',
    '                <span>Dark Mode Color Theme</span>',
    '                <label class="switch-frame">',
    '                    <input type="checkbox" id="toggle-dark" checked>',
    '                    <span class="switch-slider"></span>',
    '                </label>',
    '            </div>',
    '            <div class="control-row">',
    '                <span>Render Block Drop Shadows</span>',
    '                <label class="switch-frame">',
    '                    <input type="checkbox" id="toggle-shadow" checked>',
    '                    <span class="switch-slider"></span>',
    '                </label>',
    '            </div>',
    '            <div class="control-row">',
    '                <span>Display Matrix Names</span>',
    '                <label class="switch-frame">',
    '                    <input type="checkbox" id="toggle-names">',
    '                    <span class="switch-slider"></span>',
    '                </label>',
    '            </div>',
    '            <div class="control-row">',
    '                <span>Fullscreen Framework</span>',
    '                <button id="btn-fullscreen-toggle" style="background:var(--bg-color); border:1px solid var(--border-color); color:inherit; padding:0.4rem 0.8rem; border-radius:0.5rem; cursor:pointer; font-weight:600;">Toggle</button>',
    '            </div>',
    '            <div class="control-row" id="pwa-row" style="display:none;">',
    '                <span>Add to Home Screen</span>',
    '                <button id="btn-pwa-install" class="action-button" style="width:auto; padding:0.4rem 1rem; margin:0;">Add</button>',
    '            </div>',
    '            ',
    '            <button id="close-settings" class="action-button" style="margin-top:1rem;">Save & Exit</button>',
    '        </div>',
    '    </div>',
    '    ',
    '    ',
    '    <div id="modal-shop" class="ui-modal">',
    '        <div class="modal-body">',
    '            <h3 class="title-font" style="margin-top:0; margin-bottom:1.25rem; font-size:1.4rem; text-align:center;">Shop Engine</h3>',
    '            ',
    '            <label style="font-weight:700; font-size:0.95rem; display:block; margin-bottom:0.5rem;">Grid Configuration Unlocks</label>',
    '            <div class="size-selector">',
    '                <button class="size-btn active-size" data-size="6" id="btn-size-6">6x6</button>',
    '                <button class="size-btn locked-size" data-size="8" id="btn-size-8">8x8</button>',
    '                <button class="size-btn locked-size" data-size="10" id="btn-size-10">10x10</button>',
    '            </div>',
    '            <span style="font-size:11px; opacity:0.7; display:block; margin-top:-1rem; margin-bottom:1.25rem; text-align:center;">8x8 costs 150 coins. 10x10 costs 300 coins.</span>',
    '            ',
    '            <label style="font-weight:700; font-size:0.95rem; display:block; margin-bottom:0.25rem;">Color Skins Pool (16 Available)</label>',
    '            <span style="font-size:11px; opacity:0.7; display:block; margin-bottom:0.75rem;">Premium themes cost 50 coins. Purchased pools cycle dynamically on cleared sweeps.</span>',
    '            <div id="swatch-container" class="theme-grid"></div>',
    '            ',
    '            <button id="close-shop" class="action-button" style="margin-top:1.75rem;">Return to Arena</button>',
    '        </div>',
    '    </div>',
    '    ',
    '    <script>',
    `        const SHAPES_ENGINE = ${JSON.stringify(SHAPES_DATABASE)};`,
    `        const THEME_PALETTES = ${JSON.stringify(SHAPE_COLORS.slice(0, 16).length === 16 ? SHAPE_COLORS.slice(0, 16) : ["#3b82f6", "#ef4444", "#10b981", "#f59e0b", "#ec4899", "#8b5cf6", "#6366f1", "#14b8a6", "#f43f5e", "#06b6d4", "#84cc16", "#a855f7", "#eab308", "#f97316", "#06b6d4", "#10b981"].slice(0,16))};`,
    '        ',
    '        // Economy and unlock states stored persistently across offline play sessions',
    '        let gameState = {',
    '            gridSize: 6,',
    '            score: 0,',
    '            combo: 0,',
    '            multiplier: 1.0,',
    '            highScore: parseInt(localStorage.getItem("bb_high_offline") || "0"),',
    '            balance: parseInt(localStorage.getItem("bb_bal_offline") || "100"), // Starts with 100 base capital for testing shop mechanics',
    '            activePaletteIdx: 0,',
    '            useShadows: true,',
    '            showNames: false,',
    '            unlockedSizes: JSON.parse(localStorage.getItem("bb_sizes_offline") || \'[6]\'),',
    '            unlockedThemes: JSON.parse(localStorage.getItem("bb_themes_offline") || \'[0,1,2,3]\')',
    '        };',
    '        ',
    '        let board = [];',
    '        let trayHand = [null, null, null];',
    '        let currentDrag = null;',
    '        let deferredPrompt = null;',
    '        ',
    '        const elGrid = document.getElementById("grid-root");',
    '        const elTray = document.getElementById("tray-root");',
    '        ',
    '        function buildBoard() {',
    '            board = Array(gameState.gridSize).fill(null).map(() => Array(gameState.gridSize).fill(null));',
    '            elGrid.style.gridTemplateRows = `repeat(${gameState.gridSize}, 1fr)`;',
    '            elGrid.style.gridTemplateColumns = `repeat(${gameState.gridSize}, 1fr)`;',
    '            drawBoard();',
    '        }',
    '        ',
    '        function drawBoard() {',
    '            elGrid.innerHTML = "";',
    '            for(let r=0; r<gameState.gridSize; r++) {',
    '                for(let c=0; c<gameState.gridSize; c++) {',
    '                    const cell = document.createElement("div");',
    '                    cell.className = "cell-unit";',
    '                    cell.dataset.row = r;',
    '                    cell.dataset.col = c;',
    '                    if(board[r][c]) {',
    '                        cell.style.backgroundColor = board[r][c];',
    '                        if(gameState.useShadows) cell.classList.add("has-shadow");',
    '                    }',
    '                    elGrid.appendChild(cell);',
    '                }',
    '            }',
    '        }',
    '        ',
    '        function loadTrayHand() {',
    '            const shapeKeys = Object.keys(SHAPES_ENGINE);',
    '            // Pick exclusively from themes currently unlocked by user pocket economy',
    '            const pools = gameState.unlockedThemes;',
    '            ',
    '            for(let i=0; i<3; i++) {',
    '                const randomKey = shapeKeys[Math.floor(Math.random() * shapeKeys.length)];',
    '                const themeSelectionIdx = pools[Math.floor(Math.random() * pools.length)] || 0;',
    '                const colorHex = THEME_PALETTES[themeSelectionIdx % THEME_PALETTES.length];',
    '                ',
    '                trayHand[i] = { ',
    '                    matrix: SHAPES_ENGINE[randomKey].cells || SHAPES_ENGINE[randomKey], ',
    '                    name: SHAPES_ENGINE[randomKey].name || randomKey,',
    '                    color: colorHex ',
    '                };',
    '            }',
    '            drawTray();',
    '        }',
    '        ',
    '        function drawTray() {',
    '            elTray.innerHTML = "";',
    '            trayHand.forEach((shape, idx) => {',
    '                const dock = document.createElement("div");',
    '                dock.className = "tray-dock";',
    '                dock.dataset.slotIndex = idx;',
    '                ',
    '                if(shape) {',
    '                    const matrix = shape.matrix;',
    '                    const previewWrap = document.createElement("div");',
    '                    previewWrap.style.display = "grid";',
    '                    previewWrap.style.gridTemplateRows = `repeat(${matrix.length}, 14px)`;',
    '                    previewWrap.style.gridTemplateColumns = `repeat(${matrix[0].length}, 14px)`;',
    '                    previewWrap.style.gap = "2px";',
    '                    ',
    '                    matrix.forEach(row => {',
    '                        row.forEach(val => {',
    '                            const block = document.createElement("div");',
    '                            block.style.borderRadius = "3px";',
    '                            block.style.width = "14px";',
    '                            block.style.height = "14px";',
    '                            if(val) {',
    '                                block.style.backgroundColor = shape.color;',
    '                                if(gameState.useShadows) block.classList.add("has-shadow");',
    '                            }',
    '                            previewWrap.appendChild(block);',
    '                        });',
    '                    });',
    '                    ',
    '                    dock.appendChild(previewWrap);',
    '                    ',
    '                    if(gameState.showNames) {',
    '                        const nameLabel = document.createElement("span");',
    '                        nameLabel.innerText = shape.name;',
    '                        nameLabel.className = "helper-text";',
    '                        nameLabel.style.position = "absolute";',
    '                        nameLabel.style.bottom = "4px";',
    '                        dock.appendChild(nameLabel);',
    '                    }',
    '                    ',
    '                    dock.addEventListener("pointerdown", (e) => beginDragSequence(e, idx));',
    '                }',
    '                elTray.appendChild(dock);',
    '            });',
    '        }',
    '        ',
    '        function beginDragSequence(e, slotIndex) {',
    '            e.preventDefault();',
    '            const targetShape = trayHand[slotIndex];',
    '            if(!targetShape) return;',
    '            ',
    '            const sourceDock = e.currentTarget;',
    '            const clonedRender = sourceDock.cloneNode(true);',
    '            clonedRender.classList.add("floating-drag-element");',
    '            document.body.appendChild(clonedRender);',
    '            ',
    '            // Measure precise element sizing to dynamically clear thumb obstruction spacing',
    '            const rect = sourceDock.getBoundingClientRect();',
    '            ',
    '            currentDrag = {',
    '                slotIndex: slotIndex,',
    '                shape: targetShape,',
    '                element: clonedRender,',
    '                offsetX: rect.width / 2,',
    '                offsetY: rect.height + 15 // Lift block above finger completely to fix tracking view',
    '            };',
    '            ',
    '            trackPosition(e);',
    '            document.addEventListener("pointermove", processDragMove);',
    '            document.addEventListener("pointerup", terminateDragSequence);',
    '        }',
    '        ',
    '        function trackPosition(e) {',
    '            if(!currentDrag) return;',
    '            currentDrag.element.style.left = `${e.clientX - currentDrag.offsetX}px`;',
    '            currentDrag.element.style.top = `${e.clientY - currentDrag.offsetY}px`;',
    '        }',
    '        ',
    '        function processDragMove(e) { if(currentDrag) trackPosition(e); }',
    '        ',
    '        function terminateDragSequence(e) {',
    '            if(!currentDrag) return;',
    '            document.removeEventListener("pointermove", processDragMove);',
    '            document.removeEventListener("pointerup", terminateDragSequence);',
    '            currentDrag.element.remove();',
    '            ',
    '            // Target offset point targeted slightly above thumb for precise alignment validation',
    '            const targetX = e.clientX;',
    '            const targetY = e.clientY - currentDrag.offsetY + (currentDrag.offsetX);',
    '            ',
    '            const underPoint = document.elementFromPoint(targetX, targetY);',
    '            const targetCell = underPoint ? underPoint.closest(".cell-unit") : null;',
    '            ',
    '            if(targetCell) {',
    '                const startRow = parseInt(targetCell.dataset.row);',
    '                const startCol = parseInt(targetCell.dataset.col);',
    '                ',
    '                if(verifyPlacementFit(currentDrag.shape.matrix, startRow, startCol)) {',
    '                    applyMatrixToBoard(currentDrag.shape.matrix, currentDrag.shape.color, startRow, startCol);',
    '                    trayHand[currentDrag.slotIndex] = null;',
    '                    ',
    '                    if(trayHand.every(s => s === null)) {',
    '                        loadTrayHand();',
    '                    } else {',
    '                        drawTray();',
    '                    }',
    '                }',
    '            }',
    '            currentDrag = null;',
    '        }',
    '        ',
    '        function verifyPlacementFit(matrix, sRow, sCol) {',
    '            for(let r=0; r<matrix.length; r++) {',
    '                for(let c=0; c<matrix[r].length; c++) {',
    '                    if(matrix[r][c]) {',
    '                        const tr = sRow + r;',
    '                        const tc = sCol + c;',
    '                        if(tr >= gameState.gridSize || tc >= gameState.gridSize || tr < 0 || tc < 0 || board[tr][tc]) {',
    '                            return false;',
    '                        }',
    '                    }',
    '                }',
    '            }',
    '            return true;',
    '        }',
    '        ',
    '        function applyMatrixToBoard(matrix, colorHex, sRow, sCol) {',
    '            for(let r=0; r<matrix.length; r++) {',
    '                for(let c=0; c<matrix[r].length; c++) {',
    '                    if(matrix[r][c]) board[sRow+r][sCol+c] = colorHex;',
    '                }',
    '            }',
    '            gameState.score += 15;',
    '            gameState.balance += 2;',
    '            sweepCompleteLines();',
    '            drawBoard();',
    '            refreshScoreboard();',
    '        }',
    '        ',
    '        function sweepCompleteLines() {',
    '            let fullyClearedRows = [];',
    '            let fullyClearedCols = [];',
    '            ',
    '            for(let r=0; r<gameState.gridSize; r++) {',
    '                if(board[r].every(c => c !== null)) fullyClearedRows.push(r);',
    '            }',
    '            for(let c=0; c<gameState.gridSize; c++) {',
    '                let targetColMatch = true;',
    '                for(let r=0; r<gameState.gridSize; r++) {',
    '                    if(board[r][c] === null) { targetColMatch = false; break; }',
    '                }',
    '                if(targetColMatch) fullyClearedCols.push(c);',
    '            }',
    '            ',
    '            const linesCleared = fullyClearedRows.length + fullyClearedCols.length;',
    '            if(linesCleared > 0) {',
    '                fullyClearedRows.forEach(r => board[r].fill(null));',
    '                fullyClearedCols.forEach(c => {',
    '                    for(let r=0; r<gameState.gridSize; r++) board[r][c] = null;',
    '                });',
    '                ',
    '                gameState.combo++;',
    '                let rawPoints = linesCleared * 100;',
    '                gameState.score += Math.floor(rawPoints * gameState.multiplier);',
    '                gameState.multiplier += 0.5 * linesCleared;',
    '                gameState.balance += linesCleared * 10;',
    '                ',
    '                // Dynamic Theme Rotation: cycles through premium palettes automatically upon screen sweeps',
    '                if (gameState.unlockedThemes.length > 0) {',
    '                    const currentPoolIndex = gameState.unlockedThemes.indexOf(gameState.activePaletteIdx);',
    '                    const nextPoolIndex = (currentPoolIndex + 1) % gameState.unlockedThemes.length;',
    '                    gameState.activePaletteIdx = gameState.unlockedThemes[nextPoolIndex];',
    '                    updateActiveSwatchHighlight();',
    '                }',
    '            } else {',
    '                gameState.combo = 0;',
    '                gameState.multiplier = 1.0;',
    '            }',
    '            ',
    '            if(gameState.score > gameState.highScore) {',
    '                gameState.highScore = gameState.score;',
    '                localStorage.setItem("bb_high_offline", gameState.highScore.toString());',
    '            }',
    '            localStorage.setItem("bb_bal_offline", gameState.balance.toString());',
    '        }',
    '        ',
    '        function refreshScoreboard() {',
    '            document.getElementById("score-txt").innerText = gameState.score;',
    '            document.getElementById("combo-txt").innerText = gameState.combo;',
    '            document.getElementById("mult-txt").innerText = `x${gameState.multiplier.toFixed(1)}`;',
    '            document.getElementById("high-txt").innerText = gameState.highScore;',
    '            document.getElementById("balance-txt").innerText = gameState.balance;',
    '            renderSizesButtons();',
    '        }',
    '        ',
    '        function renderSizesButtons() {',
    '            [6, 8, 10].forEach(size => {',
    '                const btn = document.getElementById(`btn-size-${size}`);',
    '                if (gameState.gridSize === size) {',
    '                    btn.className = "size-btn active-size";',
    '                } else if (gameState.unlockedSizes.includes(size)) {',
    '                    btn.className = "size-btn";',
    '                } else {',
    '                    btn.className = "size-btn locked-size";',
    '                }',
    '            });',
    '        }',
    '        ',
    '        /* Premium UI Event Binding Layer */',
    '        document.getElementById("trigger-settings").addEventListener("click", () => document.getElementById("modal-settings").classList.add("is-open"));',
    '        document.getElementById("close-settings").addEventListener("click", () => document.getElementById("modal-settings").classList.remove("is-open"));',
    '        document.getElementById("trigger-shop").addEventListener("click", () => document.getElementById("modal-shop").classList.add("is-open"));',
    '        document.getElementById("close-shop").addEventListener("click", () => document.getElementById("modal-shop").classList.remove("is-open"));',
    '        ',
    '        // Light-Dark Mode Toggle Mechanism Fixes',
    '        document.getElementById("toggle-dark").addEventListener("change", (e) => {',
    '            document.documentElement.setAttribute("data-theme", e.target.checked ? "dark" : "light");',
    '        });',
    '        ',
    '        document.getElementById("toggle-shadow").addEventListener("change", (e) => {',
    '            gameState.useShadows = e.target.checked;',
    '            drawBoard();',
    '            drawTray();',
    '        });',
    '        ',
    '        document.getElementById("toggle-names").addEventListener("change", (e) => {',
    '            gameState.showNames = e.target.checked;',
    '            drawTray();',
    '        });',
    '        ',
    '        document.getElementById("btn-fullscreen-toggle").addEventListener("click", () => {',
    '            if (!document.fullscreenElement) {',
    '                document.documentElement.requestFullscreen().catch(() => {});',
    '            } else {',
    '                document.exitFullscreen();',
    '            }',
    '        });',
    '        ',
    '        /* Shop Grid Dimensions Transactions Logic */',
    '        document.querySelectorAll(".size-btn").forEach(btn => {',
    '            btn.addEventListener("click", (e) => {',
    '                const targetSize = parseInt(e.target.dataset.size);',
    '                const cost = targetSize === 8 ? 150 : targetSize === 10 ? 300 : 0;',
    '                ',
    '                if (gameState.unlockedSizes.includes(targetSize)) {',
    '                    gameState.gridSize = targetSize;',
    '                    gameState.score = 0; gameState.combo = 0; gameState.multiplier = 1.0;',
    '                    buildBoard(); refreshScoreboard();',
    '                } else {',
    '                    if (gameState.balance >= cost) {',
    '                        gameState.balance -= cost;',
    '                        gameState.unlockedSizes.push(targetSize);',
    '                        gameState.gridSize = targetSize;',
    '                        localStorage.setItem("bb_sizes_offline", JSON.stringify(gameState.unlockedSizes));',
    '                        localStorage.setItem("bb_bal_offline", gameState.balance.toString());',
    '                        gameState.score = 0; gameState.combo = 0; gameState.multiplier = 1.0;',
    '                        buildBoard(); refreshScoreboard();',
    '                    } else {',
    '                        alert("Insufficient Coins! Keep clearing lines to collect currency.");',
    '                    }',
    '                }',
    '            });',
    '        });',
    '        ',
    '        /* Swatch Matrix Generator with Economy Checkholds */',
    '        const swatchFrame = document.getElementById("swatch-container");',
    '        THEME_PALETTES.forEach((hex, sIdx) => {',
    '            const swatch = document.createElement("div");',
    '            swatch.style.backgroundColor = hex;',
    '            ',
    '            function updateSwatchLook() {',
    '                swatch.className = "theme-swatch";',
    '                if (sIdx === gameState.activePaletteIdx) swatch.classList.add("active-swatch");',
    '                if (!gameState.unlockedThemes.includes(sIdx)) swatch.classList.add("locked-swatch");',
    '            }',
    '            ',
    '            updateSwatchLook();',
    '            ',
    '            swatch.addEventListener("click", () => {',
    '                if (gameState.unlockedThemes.includes(sIdx)) {',
    '                    gameState.activePaletteIdx = sIdx;',
    '                    updateActiveSwatchHighlight();',
    '                    drawTray();',
    '                } else {',
    '                    if (gameState.balance >= 50) {',
    '                        gameState.balance -= 50;',
    '                        gameState.unlockedThemes.push(sIdx);',
    '                        gameState.activePaletteIdx = sIdx;',
    '                        localStorage.setItem("bb_themes_offline", JSON.stringify(gameState.unlockedThemes));',
    '                        localStorage.setItem("bb_bal_offline", gameState.balance.toString());',
    '                        updateActiveSwatchHighlight();',
    '                        refreshScoreboard();',
    '                        drawTray();',
    '                    } else {',
    '                        alert("This theme swatch requires 50 currency coins.");',
    '                    }',
    '                }',
    '            });',
    '            swatchFrame.appendChild(swatch);',
    '        });',
    '        ',
    '        function updateActiveSwatchHighlight() {',
    '            document.querySelectorAll(".theme-swatch").forEach((s, idx) => {',
    '                s.classList.remove("active-swatch");',
    '                s.classList.remove("locked-swatch");',
    '                if(idx === gameState.activePaletteIdx) s.classList.add("active-swatch");',
    '                if(!gameState.unlockedThemes.includes(idx)) s.classList.add("locked-swatch");',
    '            });',
    '        }',
    '        ',
    '        /* Home Screen App Installation Handlers */',
    '        window.addEventListener("beforeinstallprompt", (e) => {',
    '            e.preventDefault(); deferredPrompt = e;',
    '            document.getElementById("pwa-row").style.display = "flex";',
    '        });',
    '        ',
    '        document.getElementById("btn-pwa-install").addEventListener("click", () => {',
    '            if(!deferredPrompt) return;',
    '            deferredPrompt.prompt();',
    '            deferredPrompt.userChoice.then(() => {',
    '                document.getElementById("pwa-row").style.display = "none";',
    '                deferredPrompt = null;',
    '            });',
    '        });',
    '        ',
    '        // Initialize Game Runtimes',
    '        buildBoard();',
    '        loadTrayHand();',
    '        refreshScoreboard();',
    '    </script>',
    '</body>',
    '</html>'
  ].join('\n');

  try {
    const blob = new Blob([htmlContent], { type: 'text/html;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    
    const downloadBridgeLink = document.createElement('a');
    downloadBridgeLink.href = url;
    downloadBridgeLink.download = 'block-blast-offline.html';
    document.body.appendChild(downloadBridgeLink);
    downloadBridgeLink.click();
    
    setTimeout(() => {
      document.body.removeChild(downloadBridgeLink);
      URL.revokeObjectURL(url);
    }, 200);
  } catch (err) {
    console.error("Local file system bridge failure:", err);
  }
};